# Code generated by MCHP Chatbot
import os
import json
import shutil

currentDirectory = os.path.curdir
jsonDirectory = os.path.join(currentDirectory, "json")
outputDirectory = os.path.abspath(os.path.join(__file__, "../..", "./src/data"))


def read_json_files(root_dir):
    combined_data = {}

    # Walk through the directory
    for subdir, dirs, files in os.walk(root_dir):
        for file in files:
            if file.endswith(".json"):
                # Construct the file path
                file_path = os.path.join(subdir, file)
                # Read the JSON file
                with open(file_path, "r") as f:
                    data = json.load(f)
                # Use the relative path of the subdirectory as the key
                relative_subdir = os.path.relpath(subdir, root_dir)
                if relative_subdir not in combined_data:
                    combined_data[relative_subdir] = {}
                key = file.replace(".json", "")
                if key not in combined_data[relative_subdir].keys():
                    combined_data[relative_subdir][key] = {}
                combined_data[relative_subdir][key] = data[file.replace(".json", "")]

    return combined_data


def write_combined_json(combined_data, output_file):
    with open(output_file, "w") as f:
        json.dump(combined_data, f, indent=2, ensure_ascii=False)


# Replace 'your_root_directory' with the path to the root directory containing the subfolders
root_dir = jsonDirectory
# Replace 'output.json' with your desired output file name
output_file = os.path.join(outputDirectory, "info.json")

# Read all JSON files and combine them
combined_data = read_json_files(root_dir)
# Write the combined data to a single JSON file
write_combined_json(combined_data, output_file)

print("JSON compilation to output.json complete")

os.chmod(jsonDirectory, 0o777)
shutil.rmtree(jsonDirectory)

print("JSON directory removed.")
